version: '3.9'

services:

  backend:
    image: ghcr.io/bordewich-software/climb_timer_service:latest
    networks:
      - backend
  
  web:
    image: ghcr.io/bordewich-software/climb_time:latest
    ports:
      - "80:3000"
    networks:
      - backend

networks:
  backend:
